version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./employment_system-main:/app
      - ./employment_system-main/media:/app/media
      - ./employment_system-main/staticfiles:/app/staticfiles
    environment:
      - DEBUG=0
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./employment_system-main/media:/usr/share/nginx/html/media
      - ./employment_system-main/staticfiles:/usr/share/nginx/html/staticfiles
