# Generated by Django 5.2.2 on 2026-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Only verified employers can view graduate profiles and publish vacancies.'),
        ),
    ]
