# Generated by Django 5.2.2 on 2026-05-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_academicgroup_alter_alumniprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicgroup',
            name='admission_count',
        ),
        migrations.RemoveField(
            model_name='academicgroup',
            name='total_graduates',
        ),
        migrations.AlterField(
            model_name='alumniprofile',
            name='employment_status',
            field=models.CharField(choices=[('EMPLOYED_SPECIALTY', 'Работает по специальности'), ('EMPLOYED_NOT_SPECIALTY', 'Работает не по специальности'), ('SELF_EMPLOYED', 'Самозанятый / предприниматель'), ('CONTINUING_EDUCATION', 'Продолжает обучение'), ('UNEMPLOYED', 'Не работает'), ('LOST_CONTACT', 'Неизвестно')], default='UNEMPLOYED', max_length=32),
        ),
    ]